blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog_list/', views.BlogList.as_view(), name='blog_list'),
    path('write_blog/', views.CreateBlog.as_view(), name='write_blog'),
    path('details/<int:id>/', views.blog_details, name='details'),
    path('author_details/<pk>/',
         views.AuthorDetails.as_view(), name='author_details'),
    path('like/<pk>/', views.like, name='like'),
    path('unlike/<pk>/', views.unlike, name='unlike'),
    path('myblog/', views.MyBlog.as_view(), name='myblog'),
    path('editblog/<pk>/', views.EditBlog.as_view(), name='editblog'),
    path('delete/<pk>/', views.DeleteBlog.as_view(), name='delete')
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_user, name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout_user, name='logout'),
    path('edit_user/',views.edit_user,name='edit_user'),
    path('change_password/',views.password_change,name='change_password'),
    path('add_profile_pic/',views.add_profile_pic,name='add_profile_pic'),
    path('change_profile_pic/',views.change_profile_pic,name='change_profile_pic')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('login.urls'), namespace='login')),
    path('blog/', include(('blog.urls'), namespace='blog')),
    path('', views.index, name='index'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='user_all_profile')
    profile_pic = models.ImageField(
        upload_to='profile_pic')

    def __str__(self):
        return self.user.username

login/forms.py
from typing import Any, Dict
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile


class CustomSignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name',
                  'last_name', 'password1', 'password2']


class EditUser(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name','password']


class ProfilePictureForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic']

login/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.


def signup(request):
    form = forms.CustomSignUpForm()

    if request.method == 'POST':
        form = forms.CustomSignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login:login'))
    dic = {
        'form': form,
    }

    return render(request, 'login/signup.html', context=dic)


def login_user(request):
    form = AuthenticationForm()

    dic = {
        'form': form,

    }

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('login:profile'))

    return render(request, 'login/login.html', context=dic)


@login_required
def profile(request):
    dic = {}
    return render(request, 'login/profile.html', context=dic)


@login_required
def logout_user(request):
    logout(request)

    return HttpResponseRedirect(reverse('index'))


@login_required
def edit_user(request):
    form = forms.EditUser(instance=request.user)
    update = False
    if request.method == 'POST':
        form = forms.EditUser(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            form = forms.EditUser(instance=request.user)
            update = True

    return render(request, 'login/edit_user.html', context={'form': form, 'update': update})


@login_required
def password_change(request):
    current_user = request.user
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST,)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login:profile'))
    return render(request, 'login/password_change.html', context={'form': form})


@login_required
def add_profile_pic(request):
    form = forms.ProfilePictureForm()
    if request.method == 'POST':
        form = forms.ProfilePictureForm(request.POST, request.FILES)
        if form.is_valid():
            user_info = form.save(commit=False)
            user_info.user = request.user
            user_info.save()

    return render(request, 'login/add_profile_pic.html', context={'form': form})

@login_required
def change_profile_pic(request):
    current_user = request.user.user_all_profile
    form = forms.ProfilePictureForm(instance=current_user)
    if request.method == 'POST':
        form = forms.ProfilePictureForm(
            request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login:profile'))

    return render(request, 'login/add_profile_pic.html', context={'form': form})

login/templates/login/add_profile_pic.html
{% extends 'base.html' %}


{% block title %}
change Profile pic
{% endblock title %}

{% block body_block %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Change">
</form>
{% endblock body_block %}

login/templates/login/edit_user.html
{% extends 'base.html' %}

{% block title %}
Edit User
{% endblock title %}

{% block body_block %}

{% if update %}
<div class="alert alert-success">Update successfully !</div>    
{% endif %}
    
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Update" class="btn btn-success btn-m">
</form>
<a href="{% url 'login:change_password' %}" class="btn btn-warning btn-m mt-2">Change Password</a>


{% endblock body_block %}

login/templates/login/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock title %}

{% block body_block %}


    
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Login" class="btn btn-primary btn-m">
</form>

{% endblock body_block %}

login/templates/login/password_change.html
{% extends 'base.html' %}

{% block title %}
Password Change
{% endblock title %}

{% block body_block %}


    
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Change" class="btn btn-success btn-m">
</form>



{% endblock body_block %}

login/templates/login/profile.html
{% extends 'base.html' %}

{% block title %}
Profile
{% endblock title %}


{% block body_block %}

{% if user.user_all_profile %}
<img src="/media/{{user.user_all_profile.profile_pic}}" width="100" height="100" class="rounded-circle">
<p class="mt-3"><a href="{% url 'login:change_profile_pic' %}" class="btn btn-info btn-m">Change profile picture</a></p>

{% else %}
<img src="/media/profile_pic/default.avif" width="100" height="100">
<p class="mt-3"><a href="{% url 'login:add_profile_pic' %}" class="btn btn-info btn-m">Add profile picture</a></p>
{% endif %}

{% if user.is_authenticated %}
<p>username : {{user.username}}</p>
<p>email : {{user.email}}</p>
<p>First Name :{{user.first_name}}</p>
<p>Last Name :{{user.last_name}}</p>

<a href="{% url 'login:edit_user' %}" class="btn btn-info btn-m">Edit Profile</a>
{% endif %}


{% endblock body_block %}

login/templates/login/profile_details.html
{% extends 'base.html' %}

{% block title %}
Profile Details
{% endblock title %}


{% block body_block %}

{% if author.first_name %}

<h2>{{author.first_name}} {{author.last_name}}</h2>
{% else %}
<h1>{{author.username}}</h1>

{% endif %}


{% if author.user_all_profile %}
<img src="/media/{{author.user_all_profile.profile_pic}}" alt="" width="300" class="mt-5">
{% else %}
<img src="/media/profile_pic/default.avif" alt="" width="300" class="mt-5">

{% endif %}


{% endblock body_block %}

login/templates/login/signup.html
{% extends 'base.html' %}

{% block title %}
SignUp
{% endblock title %}



{% block body_block %}
<h1>SignUp</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="SignUp" class="btn btn-info btn-m">
</form>

{% endblock body_block %}