blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog_list/', views.BlogList.as_view(), name='blog_list'),
    path('write_blog/', views.CreateBlog.as_view(), name='write_blog'),
    path('details/<int:id>/', views.blog_details, name='details'),
    path('author_details/<pk>/',
         views.AuthorDetails.as_view(), name='author_details'),
    path('like/<pk>/', views.like, name='like'),
    path('unlike/<pk>/', views.unlike, name='unlike'),
    path('myblog/', views.MyBlog.as_view(), name='myblog'),
    path('editblog/<pk>/', views.EditBlog.as_view(), name='editblog'),
    path('delete/<pk>/', views.DeleteBlog.as_view(), name='delete')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('login.urls'), namespace='login')),
    path('blog/', include(('blog.urls'), namespace='blog')),
    path('', views.index, name='index'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Blog(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='author_blog')
    blog_title = models.CharField(max_length=255)
    blog_content = models.TextField(verbose_name='What is Your mind ?')
    slug = models.SlugField(max_length=1000, unique=True)
    blog_image = models.ImageField(upload_to='blog_img')
    publish_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['-publish_at']
    def __str__(self):
        return self.blog_title


class Comment(models.Model):
    blog = models.ForeignKey(
        Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField(verbose_name='Write Your Comment')
    comment_date = models.DateTimeField(auto_now_add=True)


class Like(models.Model):
    blog = models.ForeignKey(
        Blog, on_delete=models.CASCADE, related_name='like_blog')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='like_user')

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

blog/views.py
from typing import Any
from uuid import uuid4
from django.db.models.query import QuerySet
from django.contrib.auth.decorators import login_required
from django.forms.models import BaseModelForm
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from . models import Blog, Comment, Like
from .forms import CommentForm


# Create your views here.


class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ['blog_title', 'blog_content', 'blog_image']
    template_name = 'blog/write_blog.html'

    def form_valid(self, form: BaseModelForm):
        user_blog = form.save(commit=False)
        user_blog.author = self.request.user
        title = user_blog.blog_title
        user_blog.slug = title.replace(' ', '_')+"-"+str(uuid4())
        user_blog.save()
        return HttpResponseRedirect(reverse('blog:blog_list'))


class BlogList(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'
    context_object_name = 'blogs'

    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().order_by('-publish_at')


@login_required
def blog_details(request, id):
    blog = Blog.objects.get(pk=id)
    comment_form = CommentForm()
    all_comment = Comment.objects.filter(blog=blog)
    already_like = Like.objects.filter(user=request.user, blog=blog)
    if already_like:
        liked = True
    else:
        liked = False
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.blog = blog
            comment.user = request.user
            comment.save()
            return HttpResponseRedirect(reverse('blog:details', kwargs={'id': id}))
    return render(request, 'blog/blog_details.html', context={'blog': blog, 'comment_form': comment_form, 'all_comment': all_comment, 'liked': liked})


class AuthorDetails(DetailView):
    model = User
    template_name = 'login/profile_details.html'
    context_object_name = 'author'


@login_required
def like(request, pk):
    current_user = request.user
    blog = Blog.objects.get(pk=pk)
    already_liked = Like.objects.filter(user=current_user, blog=blog)
    if not already_liked:
        like_post = Like(user=current_user, blog=blog)
        like_post.save()
    return HttpResponseRedirect(reverse('blog:details', kwargs={'id': blog.pk}))


@login_required
def unlike(request, pk):
    current_user = request.user
    blog = Blog.objects.get(pk=pk)
    already_like = Like.objects.filter(user=current_user, blog=blog)
    if already_like:
        already_like.delete()
    return HttpResponseRedirect(reverse('blog:details', kwargs={'id': blog.pk}))


class MyBlog(LoginRequiredMixin, TemplateView):
    template_name = 'blog/myblog.html'


class EditBlog(LoginRequiredMixin, UpdateView):
    template_name = 'blog/editblog.html'
    model = Blog
    fields = ['blog_title', 'blog_content', 'blog_image']

    def get_success_url(self):
        return reverse_lazy('blog:details', kwargs={'id': self.object.pk})


class DeleteBlog(LoginRequiredMixin, DeleteView):
    model = Blog
    template_name = 'blog/delete.html'

    def get_success_url(self):
        return reverse_lazy('blog:myblog')

blog/templates/blog/blog_details.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}
Blog Details
{% endblock title %}




{% block body_block %}
<div class="row">
    <div class="col">
        <h3>{{blog.blog_title}}</h3>
        <h6>{{blog.publish_at}}</h6>
        <p>Posted by : {{blog.author}}</p>
        <p><i>update at : {{blog.update_at}}</i></p>
    </div>
    <div class="col">
        <img src="/media/{{blog.blog_image}}" alt="" title="{{blog.blog_title}}" width="100%">
    </div>
    <p>{{blog.blog_content|linebreaks}}</p>


    {% if liked %}

    
    <a href="{% url 'blog:unlike' pk=blog.pk%}">{{blog.like_blog.count}}<i class="fa-solid fa-heart fa-xl ml-3"></i></a>
    <!-- <a href="{% url 'blog:unlike' pk=blog.pk%}">Unlike</a><span>{{blog.like_blog.count}}</span> -->

    {% else %}
    
    <a href="{% url 'blog:like' pk=blog.pk%}">{{blog.like_blog.count}}<i class="fa-regular fa-heart fa-xl ml-3"></i></a>
   
    
    <!-- <a href="{% url 'blog:like' pk=blog.pk%}">like</a><span>{{blog.like_blog.count}}</span> -->
    {% endif %}




</div>
<div class="row p-5">
    <div class="col">
        <h3>Comments : {{blog.blog_comment.count}}</h3>

        {% for comment in all_comment %}
        <p class="mt-3"><strong>{{comment.user}}:</strong> {{comment.comment}}</p>
        <small>{{comment.comment_date}}</small>
        {% endfor %}
    </div>
    <div class="col">
        <form action="" method="post">
            {% csrf_token %}
            {{comment_form.as_p}}
            <input type="submit" value="Comment" class="btn btn-success btn-m">
        </form>


    </div>
</div>

{% endblock body_block %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}
Blog list
{% endblock title %}




{% block body_block %}

{% for blog in blogs %}
<h3>{{ blog.blog_title }}</h3>
<h6>{{blog.publish_at}}</h6>

<div class="row p-3">
    <div class="col-7">

        <img src="/media/{{blog.blog_image}}" title="{{blog.blog_title}}" width="100%">
    </div>
    <div class="col-5">
        <p>{{blog.blog_content|range_filter|linebreaks}}<a href="{% url 'blog:details' id=blog.pk %}">Read More</a></p>

        <h6>Posted by :<a href="{% url 'blog:author_details' pk=blog.author.pk%}">{{blog.author}}</a></h6>


    </div>
</div>
<hr>


{% endfor %}

{% endblock body_block %}

blog/templates/blog/delete.html
{% extends 'base.html' %}
{% load custom_filters %}



{% block title %}
Delete

{% endblock title %}


{% block body_block %}
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete" onclick="return confirm('Are You Sure?')" class="btn btn-danger btn-m">
</form>
<a href="{% url 'blog:myblog' %}" class="btn btn-warning btn-m mt-5">Cancel</a>

{% endblock body_block %}

blog/templates/blog/editblog.html
{% extends 'base.html' %}
{% load custom_filters %}



{% block title %}
Edit Blog

{% endblock title %}


{% block body_block %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Update" class="btn btn-success btn-m">
</form>

{% endblock body_block %}

blog/templates/blog/myblog.html
{% extends 'base.html' %}
{% load custom_filters %}



{% block title %}
My Blog

{% endblock title %}


{% block body_block %}

{% for blog in user.author_blog.all %}
<h3>{{ blog.blog_title }}</h3>
<h6>{{blog.publish_at}}</h6>

<div class="row py-5">
    <div class="col-7">

        <img src="/media/{{blog.blog_image}}" title="{{blog.blog_title}}" width="100%">
    </div>
    <div class="col-5">
        <p>{{blog.blog_content|range_filter|linebreaks}}<a href="{% url 'blog:details' id=blog.pk %}">Read More</a></p>
        <p><a href="{% url 'blog:editblog' pk=blog.pk %}">Edit</a></p>
        <p><a href="{% url 'blog:delete' pk=blog.pk %}">Delete</a></p>

        <h6>Posted by :<a href="{% url 'blog:author_details' pk=blog.author.pk%}">{{blog.author}}</a></h6>


    </div>
</div>
<hr>

{% endfor %}

{% endblock body_block %}

blog/templates/blog/write_blog.html
{% extends 'base.html' %}


{% block title %}
Write Blog
{% endblock title %}


{% block body_block %}
<form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Create">
</form>


{% endblock body_block %}